const test=require('node:test'),assert=require('node:assert/strict'),E=require('../dist/engine.js');
function round(upper,lower,answerUpper,answerLower){const ns=Array.from(upper).length,s=E.feedback(answerUpper+answerLower,upper+lower);return {upper,lower,states:[s.slice(0,ns),s.slice(ns)]};}
test('上下句独立字数、定位和排位同时筛选',()=>{
 const q=E.compile({lengths:[5,5],required:{all:'明月霜'},excluded:{all:'雨雪'},exact:[{line:'upper',chars:'月',positions:'4'},{line:'lower',chars:'霜',positions:'5'}],misplaced:[{line:'upper',chars:'明',positions:'1,2'},{line:'lower',chars:'月',positions:'1,2,3,4,5'}]});
 assert.deepEqual(q.errors,[]);assert.ok(q.matches('床前明月光','疑是地上霜'));assert.ok(!q.matches('疑是地上霜','床前明月光'));
});
test('上句黄色的字允许只出现在下句',()=>{const q=E.compile({lengths:[3,3],misplaced:[{line:'upper',chars:'月',positions:'2'}]});assert.ok(q.matches('山风雨','月云天'));assert.ok(!q.matches('山月雨','风云天'));assert.ok(!q.matches('山风雨','日云天'));});
test('同一个字在两句同位置不会冲突，定位可支持重复字',()=>{const q=E.compile({lengths:[3,3],exact:[{line:'upper',chars:'山',positions:'1,3'},{line:'lower',chars:'风',positions:'1'},{line:'lower',chars:'山',positions:'3'}]});assert.deepEqual(q.errors,[]);assert.ok(q.matches('山月山','风雨山'));assert.equal(q.required.all.get('山'),3);});
test('全副、上句、下句包含的计数取交集',()=>{const q=E.compile({lengths:[3,3],required:{all:'月月',upper:'月',lower:'月'}});assert.equal(q.required.all.get('月'),2);assert.ok(q.matches('月山风','月雨云'));assert.ok(!q.matches('月月风','山雨云'));const r=E.compile({lengths:[3,3],required:{all:'月月',upper:'月月',lower:'月'}});assert.equal(r.required.all.get('月'),3);assert.ok(r.matches('月月风','月雨云'));assert.ok(!r.matches('月山风','月雨云'));});
test('单句排除不错误影响另一句',()=>{assert.ok(E.compile({lengths:[3,3],required:{all:'月'},excluded:{lower:'月'}}).matches('山月明','风雨山'));assert.ok(!E.compile({lengths:[3,3],excluded:{all:'月'}}).matches('山月明','风雨山'));});
test('跨句重复字共享次数，额外灰字不全局排除',()=>{assert.deepEqual(E.feedback('山月明风雨山','雨雨云雨云云'),[1,0,0,0,0,0]);const q=E.compile({lengths:[3,3],rounds:[{upper:'雨雨云',lower:'雨云云',states:[[1,0,0],[0,0,0]]}]});assert.ok(q.matches('山月明','风雨山'));assert.ok(!q.matches('雨月明','风雨山'));});
test('下句绿字先占用次数，上句不能抢先判黄',()=>{assert.deepEqual(E.feedback('山月明风雨山','风云云风云山'),[0,0,0,2,0,2]);const q=E.compile({lengths:[3,3],rounds:[{upper:'风云云',lower:'风云山',states:[[0,0,0],[2,0,2]]}]});assert.ok(q.matches('山月明','风雨山'));});
test('每句内部有多次同字，匹配最低次数与反馈上限',()=>{const q=E.compile({lengths:[5,5],required:{upper:'处处'}});assert.ok(q.matches('处处闻啼鸟','夜来风雨声'));assert.ok(!q.matches('何处闻啼鸟','夜来风雨声'));const r=round('处处处处处','夜来风雨声','处处闻啼鸟','夜来风雨声');assert.deepEqual(r.states[0],[2,2,0,0,0]);assert.ok(E.compile({lengths:[5,5],rounds:[r]}).matches('处处闻啼鸟','夜来风雨声'));});
test('两句全部标完才参与，多轮取交集',()=>{const a='床前明月光',b='疑是地上霜';const rounds=[round('举头望明月','低头思故乡',a,b),round('白日依山尽','黄河入海流',a,b),{upper:a,lower:b,states:[[0,0,0,0,0],[-1,-1,-1,-1,-1]]}];const q=E.compile({lengths:[5,5],rounds});assert.equal(q.rounds.length,2);assert.ok(q.matches(a,b));});
test('反馈逐句核对长度，同总长度但句长不同不匹配',()=>{const r={upper:'山月明',lower:'风雨山',states:[[2,2,2],[2,2,2]]};assert.ok(E.compile({lengths:[2,4],rounds:[r]}).errors.length);const q=E.compile({lengths:[0,0],rounds:[r]});assert.deepEqual(q.lengths,[3,3]);assert.ok(!q.matches('山月','明风雨山'));assert.ok(E.compile({lengths:[0,0],rounds:[r],exact:[{line:'lower',chars:'山',positions:'4'}]}).errors.length);});
test('非法字数快速报错，未知一侧不误判总容量',()=>{for(const n of [NaN,Infinity,1e12,-1,1.5,41])assert.ok(E.compile({lengths:[n,5],required:{all:'月'}}).errors.length);assert.deepEqual(E.compile({lengths:[5,0],required:{all:'月月月月月月'}}).errors,[]);});
test('Unicode补充平面汉字与位置验证',()=>{assert.equal(E.chars('𠮷，月 A😀'),'𠮷月');assert.ok(E.compile({lengths:[2,2],exact:[{line:'upper',chars:'月',positions:'2'}]}).matches('𠮷月','山风'));assert.deepEqual(E.positions('1，3、5 5'),[1,3,5]);for(const bad of ['0','-1','2.5','1-3','41'])assert.throws(()=>E.positions(bad));});
test('完全相同上下句合并出处，不重复加入同一来源',()=>{const m=new Map(),a=['题','作者','唐','库',1],b=['题二','作者二','宋','库',2];E.addCandidate(m,'床前明月光','疑是地上霜',a);E.addCandidate(m,'床前明月光','疑是地上霜',b);E.addCandidate(m,'床前明月光','疑是地上霜',a);assert.equal(m.size,1);assert.equal([...m.values()][0].sources.length,2);E.addCandidate(m,'床前明月光','低头思故乡',a);assert.equal(m.size,2);});
test('去重保留上下句边界，原文繁简不混合',()=>{const m=new Map(),p=['题','作','唐','库',1];for(const [u,l]of [['甲乙','丙'],['甲','乙丙'],['春風','秋雨'],['春风','秋雨']])E.addCandidate(m,u,l,p);assert.equal(m.size,4);});
